name: DPP-Core
version: 1.0.0.2
main: com.darksoldier1404.duc.UniversalCore
api-version: 1.17
authors: [ DEAD_POOLIO_ ]
loadbefore:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib
  - DP-LegendaryCash
  - DP-VirtualStorage
  - DP-SimplePrefix
commands:
  dppc:
description: this plugin is include AnvilGUI from https://github.com/WesJD/AnvilGUI
